// Generated by CoffeeScript 1.4.0
(function() {
  var extend, globals, misc, pick, rdio,
    __slice = [].slice,
    __hasProp = {}.hasOwnProperty;

  pick = function() {
    var copy, key, keys, obj, _i, _len;
    obj = arguments[0], keys = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    copy = {};
    for (_i = 0, _len = keys.length; _i < _len; _i++) {
      key = keys[_i];
      copy[key] = obj[key];
    }
    return copy;
  };

  extend = function() {
    var dest, key, sources, src, value, _i, _len;
    dest = arguments[0], sources = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    for (_i = 0, _len = sources.length; _i < _len; _i++) {
      src = sources[_i];
      for (key in src) {
        if (!__hasProp.call(src, key)) continue;
        value = src[key];
        dest[key] = value;
      }
    }
    return dest;
  };

  rdio = pick(process.env, 'RDIO_CONSUMER', 'RDIO_SECRET', 'HEROKU_URL');

  misc = {
    DOMAIN: process.env.DOMAIN || process.env.HEROKU_URL,
    CALLBACK: 'auth'
  };

  module.exports = globals = extend({}, rdio, misc);

  if (!(globals.RDIO_CONSUMER && globals.RDIO_SECRET)) {
    throw new Error('Invalid rdio credentials');
  }

}).call(this);
