// Generated by CoffeeScript 1.4.0
(function() {
  var CALLBACK;

  CALLBACK = require('./globals').CALLBACK;

  module.exports = function(robot) {
    var io, listeners, routes, socketController;
    io = (require('hubot.io'))(robot);
    routes = (require('./routes'))(robot);
    listeners = (require('./listeners'))(robot);
    socketController = (require('./socket-controller'))(robot);
    robot.respond(/init rdio/i, listeners.init);
    robot.respond(/play whatever/i, listeners.playWhatever);
    robot.respond(/pause( music){0,1}/i, listeners.pause);
    robot.router.get('/', routes.home);
    robot.router.get("/" + CALLBACK, routes.auth);
    return robot.router.get('/player', routes.player);
  };

}).call(this);
