// Generated by CoffeeScript 1.4.0
(function() {
  var CALLBACK, sockets;

  sockets = require('hubot.io');

  CALLBACK = require('./globals').CALLBACK;

  module.exports = function(robot) {
    var listeners, routes;
    robot.io = sockets(robot);
    routes = (require('./routes'))(robot);
    listeners = (require('./listeners'))(robot);
    robot.respond(/init rdio/i, listeners.init);
    robot.respond(/test rdio/i, listeners.test);
    robot.router.get('/', routes.home);
    robot.router.get("/" + CALLBACK, routes.auth);
    return robot.router.get('/player', routes.player);
  };

}).call(this);
