// Generated by CoffeeScript 1.4.0
(function() {
  var compile, name, page, pages;

  compile = require('coffeecup').compile;

  pages = {
    home: function() {
      doctype(5);
      return html(function() {
        return body(function() {
          h1(this.title);
          div('#gaga', function() {
            return '';
          });
          script({
            src: '/socket.io/socket.io.js'
          });
          script({
            src: '/jquery.js'
          });
          script({
            src: '/jquery.rdio.js'
          });
          return coffeescript(function() {
            return $(function() {
              var socket;
              socket = io.connect();
              return socket.on('gaga', function(data) {
                return console.log(data);
              });
            });
          });
        });
      });
    },
    error: function() {
      return body(function() {
        return p(this.message);
      });
    },
    redirect: function() {
      input({
        type: 'hidden',
        id: 'redirect',
        value: this.redirect
      });
      return coffeescript(function() {
        var redirect;
        redirect = function() {
          var url;
          url = (document.getElementById('redirect')).value;
          return window.location.href = url;
        };
        return setTimeout(redirect, 3000);
      });
    },
    player: function() {
      return div(function() {
        return this.playbackToken;
      });
    }
  };

  for (name in pages) {
    page = pages[name];
    module.exports[name] = compile(page);
  }

}).call(this);
